FROM openjdk:21-jdk
COPY target/*.jar /app.jar

ARG SPRING_PROFILES_ACTIVE
ARG AWS_REGION
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY

WORKDIR /app
COPY target/payment-service-0.0.1-SNAPSHOT.jar app.jar

ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV AWS_REGION=${AWS_REGION}
ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY}

EXPOSE 80

ENTRYPOINT java -jar app.jar --spring.profiles.active=${SPRING_PROFILES_ACTIVE} --aws.region=${AWS_REGION} --aws.accessKey=${AWS_ACCESS_KEY} --aws.secretKey=${AWS_SECRET_KEY}
