apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      restartPolicy: Always
      containers:
        - name: payment-service
          image: 464732960253.dkr.ecr.us-west-1.amazonaws.com/pdingprod/payment-service:IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /actuator/health/pding
              port: 80
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/pding
              port: 80
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: AWS_REGION
              value: us-west-1
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "250m"
#            limits:
#              memory: "4Gi"
#              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/logs/pding/
              name: log-volume
            - mountPath: /var/tmp/pding_reports
              name: report-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /var/logs/pding/payment-service/
            type: DirectoryOrCreate
        - name: report-volume
          persistentVolumeClaim:
            claimName: efs-shared-pvc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
